### ISSUE TITLE
Cannot receive DTMF events

### ISSUE THREAD

**Issue by chris-rock** [shimaore/esl#13]
I try to listen to DTMF events. My code looks like:

```javascript
var call_handler = function () {
  this.ev.on('DTMF', function (call) {
    console.log('entered number')
  })
  this.execute('answer');
}
var server = esl.server(call_handler)
server.listen(3000);
```

It worked fine in the old 0.3.2 version, but does not work with 2.1.1. Do you have any ideas?

**Comment by shimaore** [comment]
Hopefully this got resolved on your end; just wanted to mention I posted a complete [demo](https://github.com/shimaore/useful-wind/tree/master/example) of the `useful-wind` framework I built atop `esl` with that demo reporting DTMFs on purpose to test this case.
