### ISSUE TITLE
JSON parse can't deal with unicode control characters

### ISSUE THREAD

**Issue by james-onsip** [shimaore/esl#21]
I would've made a pull request, but I'm having trouble with repo permissions, so I figured this would just save me the headache.

There is a bug in FreeSWITCH that causes SOME messages (it seems very intermittent) to come through with unicode characters, and those characters are occasionally control characters. The JSON.parse fails on that, which causes an error to be emitted.

1) This is definitely a FreeSWITCH issue primarily, but digging into that is much harder than stripping the characters out on this end (for now). The characters always seem to pop up in the gruu portion of 'variable_sip_recover_contact'.

2) Maybe this is exactly why this error is being emitted in the first place, and if so, I guess no change would be necessary.

Adding this line right above the JSON.parse:
body = body.replace(/[\x00-\x1F\x7F-\x9F]/g, "");

strips out those characters and avoids this. In all cases for us, we still value the contents of this message, so error'ing out on it was not an option. I do plan to explore further into FreeSWITCH to hopefully get this fixed the right way, but in the meantime this is adequate for us, so I thought maybe it would be helpful to others.

**Comment by shimaore** [comment]
Posted in 3.0.1.

**Comment by james-onsip** [comment]
Thanks for the quick response and addition! For anyone curious where this ends up on the FreeSWITCH end, I've opened an issue over there:

https://freeswitch.org/jira/browse/FS-7521
