### ISSUE TITLE
Event Socket server

### ISSUE THREAD

**Issue by poison766** [shimaore/esl#22]
Hello.
I try to use you lib for writing event server which capture channel events. My Idea I originate call for freeswitch and from the freeswitch XML dialplan I connect to an Event Socket server and I found that  event server capture only CHANNEL_HANGUP, CHANNEL_UNPARK, CHANNEL_EXECUTE_COMPLETE, CHANNEL_STATE, CHANNEL_CALLSTATE, CHANNEL_HANGUP_COMPLETE events. In that case I don't know how to process my call correctly. Can you help me ?

**Comment by shimaore** [comment]
You need to use the [higher-level commands](https://shimaore.github.io/esl/docs/response.coffee.html#section-23); most of the time you will use `this.command_uuid()` in client mode, `this.command()` in server mode.
