### ISSUE TITLE
Basic streaming of events?

### ISSUE THREAD

**Issue by avimar** [shimaore/esl#23]
Hi sorry to bother you, but can you please provide an example, in normal javascript, of simply connecting and getting all events to display similar to the output in freeswitch.log?

I see all sorts of server and client samples to execute commands, but I can't put my finger on a basic "listen to all events" example.

Thanks!

**Comment by james-onsip** [comment]
Hi avimar,

Firstly, I hope @shimaore doesn't mind me helping out here, and I would defer to him if something I say here is wrong.

Using the [event_json](https://github.com/shimaore/esl/blob/master/src/response.coffee.md#event_json) function with argument 'ALL' will make all events coming out of FreeSwitch reach your inbound channel. Filtering and other more complex arguments can be found in [Freeswitch documentation](https://wiki.freeswitch.org/wiki/Mod_event_socket#event).

As for a basic example, I'm sure you can loop through all the events, setting up a listener on each one, and have those print out. Maybe there is an easier way without touching the library, but adding a log line at the [bottom of parser.process](https://github.com/shimaore/esl/blob/master/src/esl.coffee.md#event-content) should log every single event that comes in.

Good luck,
James

**Comment by shimaore** [comment]
Thank you @james-onsip ! :)
Only thing I wanted to add was [Message Tracing](https://github.com/shimaore/esl#message-tracing): basically setting (`process.env.`) `DEBUG` to `esl:response` will show a lot of information; in this case the `emit` events and their parameters are what you are looking for.
