### ISSUE TITLE
Promise rejected by response.once() is not handled in send() nor in api()

### ISSUE THREAD

**Issue by kidplug** [shimaore/esl#25]
If an exception occurs in `response.prototype.once()` (line 53), the promise is rejected.
However, the calls to once() - from `send()` and `api()` do NOT handle the rejection.
This leads to an `unhandledRejection` event from `process`.  It would be better to transfer the error into the promise that was returned from `send()` and `api()` so that the caller receives it.

**Comment by shimaore** [comment]
I believe this is finally corrected. Since there is such a major change in the behavior of error handling (which might break existing code, although all tests in the test suite pass without modifications) I'll be releasing this as a new major version (hence 4.0).
