### ISSUE TITLE
method var in queueable loop retains last value (not captured in closure)

### ISSUE THREAD

**Issue by kidplug** [shimaore/esl#26]
This isn't really a *bug* now since the queable array is only `api`. (line 513 in response)

But if you add another item:  `[ 'api', 'bgapi' ]`
the `method` var (at line 521) retains the value of `bgapi` and `queue_api` instead calls `bgapi`

Either capture the method var in a closure, or use block level `let` assignment to capture it (ES6).

**Comment by kidplug** [comment]
or use 
`
queables.each(function(method){
});
`

**Comment by kidplug** [comment]
sorry i'm awful with coffeescript syntax...

**Comment by shimaore** [comment]
@kidplug that was a fine issue report, thank you!
