### ISSUE TITLE
Buffer is not empty at end of stream

### ISSUE THREAD

**Issue by gendalf** [shimaore/esl#28]
(err): Error: read ECONNRESET
(err):   at exports._errnoException (util.js:837:11)
(err):   at TCP.onread (net.js:544:26)
(err): 
(err): events.js:141
(err):       throw er; // Unhandled 'error' event
(err):       ^
(err): 
(err): Error: { error: 'Buffer is not empty at end of stream',
(err):   buffer: <Buffer 7b 22 45 76 65 6e 74 2d 4e 61 6d 65 22 3a 22 43 48 41 4e 4e 45 4c 5f 48 41 4e 47 55 50 5f 43 4f 4d 50 4c 45 54 45 22 2c 22 43 6f 72 65 2d 55 55 49 44 ... > }
(err):   at FreeSwitchParser.module.exports.FreeSwitchParser.on_end (/home/apps/node_modules/esl/lib/parser.js:75:42)
(err):   at Socket.<anonymous> (/home/apps/node_modules/esl/lib/parser.js:22:24)
(err):   at emitNone (events.js:72:20)
(err):   at Socket.emit (events.js:166:7)
(err):   at endReadableNT (_stream_readable.js:893:12)
(err):   at doNTCallback2 (node.js:429:9)
(err):   at process._tickCallback (node.js:343:17)

**Comment by shimaore** [comment]
Are you testing with the latest (4.1.0) release on npm? This should not throw anymore but [emit an error](https://github.com/shimaore/esl/blob/master/src/parser.coffee.md#dispatch-incoming-data-into-the-header-or-body-parsers).
