### ISSUE TITLE
How to get multi digit ivr dtmf ?

### ISSUE THREAD

**Issue by KiPSOFT** [shimaore/esl#31]
Hi;

Thanks for library. My problem, i want to get multi digit ivr dtmf code but dtmf event triggred every pressed key. How to catch play_and_get_digits command result ?

Thanks.

**Comment by KiPSOFT** [comment]
i'm solved my problem. i'm used CHANNEL_EXECUTE_COMPLETE event and get my variable declared on play_and_get_digits command.

Thanks.

**Comment by shimaore** [comment]
Yes, `execute` returns immediately while `command` waits for the matching `CHANNEL_EXECUTE_COMPLETE`. :)
I've started writing a [new documentation page](http://shimaore.github.io/esl/#using-freeswitch-commands) which hopefully has more details on the different operations.
