### ISSUE TITLE
Implement Reconnections

### ISSUE THREAD

**Issue by ggarber** [shimaore/esl#33]
It would be nice if the library automatically reconnects after a freeswitch restart (or other connectivity issue).

**Comment by shimaore** [comment]
Indeed :)
In the meantime using the extra/last parameter to the `client` function *might* work; you could try something like:

    var start = function(error) {
       if(error) { /* log... */ }

       FS.client(handler,start);
    };
    start();

although I haven't tested it and I'm not sure connectivity issues would trigger it -- all things to be tested ;)

**Comment by shimaore** [comment]
There is a new method `keepConnected()` which can be used instead of `connect()`; it will restart the connection on errors.
