### ISSUE TITLE
npm install esl

### ISSUE THREAD

**Issue by freeneutron** [shimaore/esl#37]
npm WARN package.json esl@0.0.1 No description
npm WARN package.json esl@0.0.1 No repository field.
npm WARN package.json esl@0.0.1 No README data
npm WARN package.json esl@0.0.1 No license field.
npm WARN install Refusing to install esl as a dependency of itself

**Comment by shimaore** [comment]
Current version is 5.2.2, what does `npm --verbose install esl` say?
