### ISSUE TITLE
Unhandled content type "text/rude-rejection"

### ISSUE THREAD

**Issue by Rojuinex** [shimaore/esl#40]
Seems Freeswitch responds to bad ACL with this text/rude-rejection content type.  It would be awesome if this was supported.

**Comment by shimaore** [comment]
There are a handful of errors which are stream-related and are emitted on the socket itself:
- `JSON error`
- `Missing Content-Type`
- `Unhandled Content-Type`
- `Buffer is not empty at end of stream`

and for outbound event socket (`FS.server`) any exception in the handler is also reported on the socket.

The default behavior for a socket on socket error is to close the stream, but for an inbound event socket (`FS.client`) you should still be able to catch the error and restart.

Using something similar to the following should do the trick (I haven't tested this code):

```javascript
var client = FS.client(options,handler,report);
client.on('error',function(error){
  if(error.when === 'Unhandled Content-Type' && error.error === 'text/rude-rejection') {
    // handle rude-rejection
  } else {
    // do something else with the other errors
}})
// client.connect() etc.
```

**Comment by shimaore** [comment]
This should be fixed in `master` and included in the next release. (The error reporting will change however, so the example above will not work anymore to handle unknown errors.)

**Comment by shimaore** [comment]
Integrated in v8.0.0
