### ISSUE TITLE
client.keepConnected does not seem to function properly

### ISSUE THREAD

**Issue by newtondev** [shimaore/esl#44]
Judging by the code it seems that this should handle automatic re-connection to a disconnected or dropped FreeSwitch connection, however it never seems to work or reconnect in my case. When sending commands it always returns and error: 

`{ [Error]
  res: {},
  args: 
   { when: 'send on closed socket',
     command: 'sendmsg',
     args: 
      { 'execute-app-name': 'reloadxml',
        'execute-app-arg': '',
        'call-command': 'execute' } } }`

The code I am trying to use is as follows:

`let eslClient;
let client = esl.client(function () {
    eslClient = this;
  }, (err) => {
    log('ERROR!', err);
  }
);
client.keepConnected(8021, '127.0.0.1')`

So 'eslClient' is used to call on the commands like reloadxml, however when I stop FreeSwitch, then start it back up, it never seems to create the new socket connection. You help would be really appreciated. Thanks

**Comment by newtondev** [comment]
Just finished this solution and seems to do the job:

`let client;
// Connect "inbound" to Freeswitch ESL:
const reconnect = () => {
  console.log('Reconnecting!');
  if (client) {
    client.destroy();
  }

  client = esl.client(function() {
      eslClient = this;
    }, (err) => {
      log('ERROR!', err);
    }
  );
  client.connect(8021, '127.0.0.1');

  client.on('error', function(err) {
    log('ERROR!', err);
    if (err.code === 'ECONNREFUSED') {
      setTimeout(() => {
        reconnect();
      }, 5000);  
    }
  });
}
reconnect();`

**Comment by shimaore** [comment]
@newtondev hmmm.. the code was changed recently (in 7.0.0), but older versions should be as bad as the current one. I'm not sure why I coded `keepConnected` this way, there's no way it can work. :(

One needs to (re)create a new socket as you described. I'll factorize `keepConnected` out into a new object.

**Comment by shimaore** [comment]
This patch removes the broken `keepConnected`.

The new feature is exported as `reconnect( `[`connect_options`](https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener)`, [options,] handler [,report] )` and works similarly to `client([options,]handler[,report])` but keeps the connection open. It returns a function which will terminate the connection attempts:
    
```
var stop_client = FS.reconnect({host:'127.0.0.1',port:8021},handler);
…
stop_client()
```

**Comment by shimaore** [comment]
Integrated in v8.0.0
