### ISSUE TITLE
Example of streaming out and streaming in audio

### ISSUE THREAD

**Issue by aybhalala** [shimaore/esl#60]
Hi,
I am trying to use this module to stream in and out dynamic audio. My basic setup is as follows:
1. Call comes in, it is forwarded to the socket via dialplan (Done)
2. The application takes the stream and forwards it to dialogflow (google nlu platform)
3. dialogflow returns the audio which is then streamed back via socket

I am looking for any direction on how 2 and 3 above can be done. TIA.

**Comment by aybhalala** [comment]
@shimaore I am sure you might be busy. If you get a chance, a simple suggestion would also be helpful.

**Comment by shimaore** [comment]
@aybhalala this module only provides a way to interface with FreeSwitch programmatically from Node.js using FreeSwitch's event-socket interface; you should first figure out how to get FreeSwitch to interface with the external applications you need, i.e. typically how you would do things from the existing XML dialplan. I can't really give guidance on how to interface with DialogFlow, I've never used it; this is probably best answered on the regular FreeSwitch support channels.

In event-socket you may stream realtime audio in a way that can easily be intercepted by using the [`unicast`](https://freeswitch.org/confluence/display/FREESWITCH/mod_event_socket#mod_event_socket-3.9.1.3unicast) command from event-socket (although using Node.js for media relay is probably not best). Of course it's also possible to use the regular call-setup commands (`bridge`, etc) to set regular SIP/WebRTC/… channels up.
